[build]
  command = "npm run build"
  publish = "dist"
  environment = { 
    VITE_SUPABASE_URL = "https://gwokvseuusbdaifrzyml.supabase.co", 
    VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3b2t2c2V1dXNiZGFpZnJ6eW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk2MDE4NDksImV4cCI6MjA0NTE3Nzg0OX0.dFCd5fCF71GdAzFX6yBbS2AVh9gvt-W7CVGtSASSQE4"
  }
